name: Sync to Public Repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Remove private files
        run: |
          rm -f .env* vercel.json || true

      - name: Push to public mirror
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git config user.name "Wave Bot"
          git config user.email "bot@gitsink.tech"
          git remote add public https://$TOKEN@github.com/Coffee-Room/gitsink_frontend.git
          git push --force public main:main
