name: Sync to Public Repo

on:
  push:
    branches: [main]

jobs:
  mirror:
    if: github.repository == 'Enochthedev/Gitsink'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Remove private files
        run: |
          rm -f .env* vercel.json || true
      - name: Debug Token Permissions
        run: |
          git ls-remote https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Coffee-Room/gitsink_frontend.git

      - name: Push to public mirror
        run: |
          git config user.name "Wave Bot"
          git config user.email "bot@gitsink.tech"
          git remote add public https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Coffee-Room/gitsink_frontend.git
          git push --force public main:main
