name: Sync All Coffee-Room Codebases

on:
  push:
    branches: [main]

jobs:
  sync:
    if: github.repository == 'Enochthedev/Gitsink'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Push updates to other repos
        env:
          TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          REPOS: ${{ secrets.SYNC_REPOS }}
        run: |
          git config user.name "Wave Bot"
          git config user.email "bot@gitsink.tech"
          for repo in $REPOS; do
            echo "Syncing $repo"
            git push --force "https://$TOKEN@github.com/${repo}.git" main:main
          done

